AWSTemplateFormatVersion: '2010-09-09'
Description: DAX Lambda Cluster Setup
Mappings:
  RegionMap:
    us-east-2:
      AZ1: us-east-2a
      AZ2: us-east-2b
Resources:
  DaxLambda:
    Properties:
      CodeUri: s3://test-iad-sean-myers/571c2212d5306e345d3eee2043668d8e
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /resources/{resourceId}
          Type: Api
      Handler: index.get
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  DaxLambdaPut:
    Properties:
      CodeUri: s3://test-iad-sean-myers/571c2212d5306e345d3eee2043668d8e
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        PutResource:
          Properties:
            Method: put
            Path: /resources/{resourceId}
          Type: Api
      Handler: index.put
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  Table:
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
